# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1224, 798)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ImageAq = QtWidgets.QFrame(self.centralwidget)
        self.ImageAq.setGeometry(QtCore.QRect(10, 50, 861, 51))
        self.ImageAq.setStyleSheet("border: 1px solid grey;\n"
"")
        self.ImageAq.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ImageAq.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ImageAq.setObjectName("ImageAq")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ImageAq)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.ImageAq)
        self.label_2.setStyleSheet("font: 10pt \"Arial\";\n"
"border: 0px;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.ImageAq)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.Browse = QtWidgets.QPushButton(self.ImageAq)
        self.Browse.setStyleSheet(" border: 1px solid grey;\n"
"  color: white;\n"
"  padding: 5px 5px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"font: 10pt \"Arial\";\n"
"background-color: rgb(0, 85, 127);")
        self.Browse.setObjectName("Browse")
        self.horizontalLayout.addWidget(self.Browse)
        self.pushButton = QtWidgets.QPushButton(self.ImageAq)
        self.pushButton.setStyleSheet(" border: 1px solid grey;\n"
"  color: white;\n"
"  padding: 5px 5px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"font: 10pt \"Arial\";\n"
"background-color: rgb(0, 85, 127);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 204, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.UndoBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.UndoBtn.setStyleSheet(" border: 1px solid grey;\n"
"  color: white;\n"
"  padding: 5px 5px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"font: 10pt \"Arial\";\n"
"background-color: rgb(0, 85, 127);")
        self.UndoBtn.setObjectName("UndoBtn")
        self.horizontalLayout_2.addWidget(self.UndoBtn)
        self.UndoAllBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.UndoAllBtn.setStyleSheet(" border: 1px solid grey;\n"
"  color: white;\n"
"  padding: 5px 5px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"font: 10pt \"Arial\";\n"
"background-color: rgb(0, 85, 127);")
        self.UndoAllBtn.setObjectName("UndoAllBtn")
        self.horizontalLayout_2.addWidget(self.UndoAllBtn)
        self.DisplayImage = QtWidgets.QLabel(self.centralwidget)
        self.DisplayImage.setGeometry(QtCore.QRect(20, 120, 841, 571))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DisplayImage.setFont(font)
        self.DisplayImage.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.DisplayImage.setAlignment(QtCore.Qt.AlignCenter)
        self.DisplayImage.setObjectName("DisplayImage")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(890, 230, 311, 451))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.frame_5)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.blur_slider = QtWidgets.QSlider(self.widget)
        self.blur_slider.setMinimum(1)
        self.blur_slider.setMaximum(10)
        self.blur_slider.setSingleStep(1)
        self.blur_slider.setPageStep(10)
        self.blur_slider.setProperty("value", 1)
        self.blur_slider.setTracking(True)
        self.blur_slider.setOrientation(QtCore.Qt.Horizontal)
        self.blur_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.blur_slider.setTickInterval(1)
        self.blur_slider.setObjectName("blur_slider")
        self.verticalLayout_3.addWidget(self.blur_slider)
        self.verticalLayout_5.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.frame_5)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.gamma_slider = QtWidgets.QSlider(self.widget_2)
        self.gamma_slider.setMinimum(0)
        self.gamma_slider.setMaximum(100)
        self.gamma_slider.setSingleStep(1)
        self.gamma_slider.setProperty("value", 50)
        self.gamma_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gamma_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.gamma_slider.setTickInterval(10)
        self.gamma_slider.setObjectName("gamma_slider")
        self.verticalLayout_4.addWidget(self.gamma_slider)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.frame_5)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.sharpen_slider = QtWidgets.QSlider(self.widget_3)
        self.sharpen_slider.setMinimum(1)
        self.sharpen_slider.setMaximum(50)
        self.sharpen_slider.setSingleStep(1)
        self.sharpen_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sharpen_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sharpen_slider.setTickInterval(5)
        self.sharpen_slider.setObjectName("sharpen_slider")
        self.verticalLayout_6.addWidget(self.sharpen_slider)
        self.verticalLayout_5.addWidget(self.widget_3)
        self.SaveImageBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SaveImageBtn.setGeometry(QtCore.QRect(770, 700, 93, 28))
        self.SaveImageBtn.setObjectName("SaveImageBtn")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(890, 120, 301, 81))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.EqualisationBtn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EqualisationBtn.setFont(font)
        self.EqualisationBtn.setObjectName("EqualisationBtn")
        self.LogTransformBtn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LogTransformBtn.setFont(font)
        self.LogTransformBtn.setObjectName("LogTransformBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1224, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuedit = QtWidgets.QMenu(self.menubar)
        self.menuedit.setObjectName("menuedit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen_Recent = QtWidgets.QAction(MainWindow)
        self.actionOpen_Recent.setObjectName("actionOpen_Recent")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.action_UndoAll = QtWidgets.QAction(MainWindow)
        self.action_UndoAll.setObjectName("action_UndoAll")
        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.action_SaveAndExit = QtWidgets.QAction(MainWindow)
        self.action_SaveAndExit.setObjectName("action_SaveAndExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_Recent)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.action_SaveAndExit)
        self.menuFile.addAction(self.actionExit)
        self.menuedit.addAction(self.actionUndo)
        self.menuedit.addAction(self.action_UndoAll)
        self.menuHelp.addAction(self.actionManual)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuedit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionOpen_Recent)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.action_UndoAll)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.action_SaveAndExit)
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">Load Image</span></p></body></html>"))
        self.Browse.setText(_translate("MainWindow", "Browse"))
        self.pushButton.setText(_translate("MainWindow", "Capture"))
        self.UndoBtn.setText(_translate("MainWindow", "Undo"))
        self.UndoAllBtn.setText(_translate("MainWindow", "Undo All"))
        self.DisplayImage.setText(_translate("MainWindow", "No image loaded"))
        self.label_3.setText(_translate("MainWindow", "Blur"))
        self.label_4.setText(_translate("MainWindow", "Gamma Correction"))
        self.label_5.setText(_translate("MainWindow", "Sharpening"))
        self.SaveImageBtn.setText(_translate("MainWindow", "Save Image"))
        self.EqualisationBtn.setText(_translate("MainWindow", "Apply Histogram Equalisation"))
        self.LogTransformBtn.setText(_translate("MainWindow", "Apply Log Transformation"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuedit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "&Open&"))
        self.actionSave.setText(_translate("MainWindow", "&Save&"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpen_Recent.setText(_translate("MainWindow", "Open Recent"))
        self.actionUndo.setText(_translate("MainWindow", "&Undo&"))
        self.action_UndoAll.setText(_translate("MainWindow", "&UndoAll&"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))
        self.action_SaveAndExit.setText(_translate("MainWindow", "&SaveAndExit&"))

